project:
  type: website
  # output-dir: docs

website:
  title: "Rabin Ojha"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: maps.qmd
        text: Maps
      # - href: blogs.qmd
      #   text: Blogs
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: https://www.linkedin.com/in/rabin-ojha-a42585146/
      - text: "{{< iconify ic:round-email >}}" 
        href: mailto:rabenojha@gmail.com

  page-footer:
    background: "#cdcfd2"
    center: |
      Made with [Quarto](https://quarto.org) by Rabin Ojha, 2024
      
    
      

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      # dark: darkly
    css: styles.css
    lang: en
    