
# Technical Skills

::: {.grid}

::: {.g-col-6}
- **GIS Softwares**: QGIS and ArcGIS (including PyQGIS and ArcPy)
- **Web Development**: HTML, CSS and JavaScript
- **Version control tool**: Git
:::

::: {.g-col-6}
- **Programming Language**: Python
- **Cloud Platform**: Google Earth Engine
- **Others**: OpenStreetMap, eCognition, Quarto, Overleaf, Adobe Illustrator, etc. 
:::

:::

# Work Experience

* **Research Assistant (March 2024 - now)** , [Heidelberg Institute for Geoinformation Technology (HeiGIT)](https://heigit.org/){target="_blank"}, Germany

* **Remote Sensing Analyst Intern (Summer 2022)**, [German Aerospace Center (DLR)](https://www.dlr.de/en/eoc/){target="_blank"}, Germany

* **Commodity Insights - Data Assistant (*January 2022 - June 2022*)** , [Aldi Süd Holdings](https://aldi-sued-holding-careers.com/about-us/aldi-sued-holding){target="_blank"}, Austria 

* **GIS Analyst (October 2019 - July 2021)** , [Kathmandu Living Labs](https://kathmandulivinglabs.org/){target="_blank"}, Nepal

# Education 

* **Master's Degree in Earth Observation, Geoinformatics and Geovisualization (2021-2023)**  from [University of Salzburg](https://www.plus.ac.at/geoinformatik/?lang=en){target="_blank"}, Austria and [Palacký University Olomouc](https://www.geoinformatics.upol.cz/department/){target="_blank"}, Czechia under the *Erasmus Mundus Scholarship*

* **Bachelor's Degree in Geomatics Engineering (2015-2019)** from [Tribhuvan University](https://ioepas.edu.np/){target="_blank"}, Nepal



